### ISSUE TITLE
`yarn dev` fails

### ISSUE THREAD

**Issue by fredericojordan** [kaluabentes/static-website-boilerplate#1]
I've cloned the repo @ commit 2bfb9d52efb3bf3f39dbdd7d5f1bb1490ebd563d and after running `yarn` with success, I get this error when running `yarn dev`:

```shell
~/d/static-website-boilerplate (master|✔) > yarn dev
yarn run v1.10.1
$ webpack-dev-server
/Users/fredericojordan/dev/static-website-boilerplate/src/config/routes.js:1
(function (exports, require, module, __filename, __dirname) { export default [
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by fredericojordan** [comment]
```shell
~/d/static-website-boilerplate (master|✔) > node --version
v11.8.0
~/d/static-website-boilerplate (master|✔) > yarn --version
1.10.1
```

**Comment by fredericojordan** [comment]
[`git bisect`](https://git-scm.com/docs/git-bisect) tells me that dc2697eebecafff04821934aab49a3dbfabca7da is the faulty commit!

**Comment by fredericojordan** [comment]
I was able to fix it by changing this line on `src/config/routes.js`, from
```js
export default [
```
to
```js
module.exports = [
```

Checkout PR #2.

**Comment by fredericojordan** [comment]
Thanks, Kaluated! 👍
